camera:
  - platform: unsplash
    api_key: !secret unsplash_access_key

#  - platform: generic
#    name: "Grow PiCam"
#    still_image_url: http://10.50.1.82/picture/3/current/
#    stream_source: http://10.50.1.82:8083
##    still_image_url: http://hassio:8123/api/hassio_ingress/cB868q-90Wdmm7LT-bBf410H_MLn9VuEzflSrTJbX10/picture/4/current/
##    stream_source: http://hassio:8123/api/hassio_ingress/cB868q-90Wdmm7LT-bBf410H_MLn9VuEzflSrTJbX10/picture/4/frame/
#    verify_ssl: false
#    framerate: 1
  
  #- platform: generic
  #  name: "Grow JoistCam"
  #  still_image_url: http://10.50.1.82/picture/1/current/
  #  stream_source: http://10.50.1.82:8081
  ##  still_image_url: http://hassio:8123/api/hassio_ingress/cB868q-90Wdmm7LT-bBf410H_MLn9VuEzflSrTJbX10/picture/3/current/
  ##  stream_source: http://hassio:8123/api/hassio_ingress/cB868q-90Wdmm7LT-bBf410H_MLn9VuEzflSrTJbX10/picture/3/frame/
  #  verify_ssl: false
  #  framerate: 1

  #- platform: generic
  #  name: "Tent PiCam"
  #  still_image_url: http://10.50.1.81/picture/1/current/
  #  stream_source: http://10.50.1.81:8081
  ##  still_image_url: http://hassio:8123/api/hassio_ingress/cB868q-90Wdmm7LT-bBf410H_MLn9VuEzflSrTJbX10/picture/2/current/
  ##  stream_source: http://hassio:8123/api/hassio_ingress/cB868q-90Wdmm7LT-bBf410H_MLn9VuEzflSrTJbX10/picture/2/frame/
  #  verify_ssl: false
  #  framerate: 1
  
  ##- platform: generic
  ##  name: "MommyCam"
  ##  still_image_url: http://gropi_smithers.cirfis.org/picture/1/current/
  ##  stream_source: http://10.50.1.83:8081
  ##  verify_ssl: false
  ##  framerate: 1
