# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret adam_IP
    - !secret manx_IP
    - !secret munk_IP
#  base_url: https://homeassistant.ourhouse.services
  ip_ban_enabled: false
