notify:
  - name: boulder_html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret gmail

#  - name: cirfis_telegram
#    platform: telegram
#    chat_id: !secret chat_id_1
