panel_iframe:
  #foldingathome:
  #    title: Folding@home
  #    icon: mdi:bacteria-outline
  #    url: http://hassio.cirfis.org:7396
  
  #grafana:
  #  title: Grafana
  #  icon: si:grafana
  #  #url: http://hassio/api/hassio_ingress/cJhp2nh4q0fjQ0uDzyaacryHcpEC7PmZp5Tl5eDN7RI/d/rYdddlPWk/
  #  url: http://anfractus.cirfis.org:3000/
