#- platform: unsplash
#  api_key: !secret unsplash_access_key

- platform: generic
  name: "GrowCam Shelving"
  still_image_url: http://gropi_sheldon.cirfis.org/picture/1/current/
  stream_source: http://gropi_sheldon.cirfis.org/picture/1/frame/
#  stream_source: http://gropi:8080
  verify_ssl: false
  framerate: 5
  
- platform: generic
  name: "GrowCam Ceiling"
  still_image_url: http://gropi_cecilia.cirfis.org/picture/1/current/
  stream_source: http://gropi_cecilia.cirfis.org/picture/1/frame/
#  stream_source: http://gropi:8080
  verify_ssl: false
  framerate: 5
  
- platform: generic
  name: "Tent Cam"
  still_image_url: http://tenti.cirfis.org/picture/1/current/
  stream_source: http://tenti.cirfis.org/picture/1/frame/
#  stream_source: http://tenti:8080
  verify_ssl: false
  framerate: 8