#- platform: unsplash
#  api_key: !secret unsplash_access_key

- platform: generic
  name: "Grow Room Cam"
  still_image_url: http://gropi.cirfis.org/picture/1/current/
  stream_source: http://gropi.cirfis.org/picture/1/frame/
  verify_ssl: false
  framerate: 12
  
- platform: generic
  name: "Tent Cam"
  still_image_url: http://tenti.cirfis.org/picture/2/current/
  stream_source: http://tenti.cirfis.org/picture/2/frame/
  verify_ssl: false
  framerate: 8