# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#python_script:
#ios:
#mobile_app:

system_health:
zeroconf:
config:
map:
#person:

sun:

hacs:
  token: !secret github_hacs_token
  sidepanel_title: HACS
  sidepanel_icon: "mdi:cloud-circle"
  options:
    experimental: true

#browser_mod:

#spotify:
#  client_id: !secret spotify_client_id
#  client_secret: !secret spotify_client_secret

ssdp:
updater:
  reporting: False
#  enable: False

history:
  exclude:
    domains:
#      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date

uilogs:
logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: debug



logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
    domains:
      - sun
      - weblink


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret adam_IP
    - !secret manx_IP
    - !secret munk_IP
#  base_url: https://homeassistant.ourhouse.services

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js
    
    
discovery:
#  enable:
#    - dlna_dmr

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: ""
  default_measurement: state  
  max_retries: 5
  tags_attributes:
    - friendly_name

#prometheus:
#  namespace: hassio

#telegram_bot:
#  platform: broadcast
#  api_key: !secret telegram_api_homey
#  allowed_chat_ids:
#    - 841656683

#input_datetime:
#  both_date_and_time:
#    name: Input with both date and time
#    has_date: true
#    has_time: true
#  only_date:
#    name: Input with only date
#    has_date: true
#    has_time: false
#  only_time:
#    name: Input with only time
#    has_date: false
#    has_time: true

#device_sun_light_trigger:


group: !include groups.yaml
automation: !include automations.yaml
device_tracker: !include trackers.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
weather: !include weather.yaml
media_player: !include media_player.yaml
camera: !include cameras.yaml
script: !include scripts.yaml
notify: !include notify.yaml
panel_iframe: !include panels.yaml

#keyboard_remote: !include keyboard_remotes.yaml
