homeassistant:
  name: OurHouse
  latitude: 43.0381
  longitude: -83.8093333
  elevation: 198
  unit_system: imperial
  currency: USD
  time_zone: "America/Detroit"
  external_url: "https://6429.casa"
  internal_url: "http://hassio.cirfis.org:8123"
  allowlist_external_dirs:
    - "/tmp"
  #    - "/Media/media"
  #    - "/Media/downloads"
  #    - "/Data/housestack"
  #    - "/Data/backups"
  allowlist_external_urls:
    - "http://hassio:8123"
    - "http://veterno.cirfis.org:8123"
    - "http://hassio.cirfis.org:8123"
    - "https://6429.casa"
    - "https://www.6429.casa"
    - "https://homeassistant.6429.casa"
    - "https://hassio.6429.casa"
    - "https://homeassistant.ourhouse.services"
    - "https://hassio.ourhouse.services"
    - "https://homeassistant.cirfis.org"
  #    - "https://veterno.cirfis.org"
  #  media_dirs:
  #    media: /Media/media
  #    recordings:
  legacy_templates: false
  #  auth_providers:
  #    - type: homeassistant
  #- type: legacy_api_password
  #  api_password: !secret legacy_api_password

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

  packages: !include_dir_named packages
