homeassistant:
  legacy_templates: false
  
  auth_providers:
    - type: homeassistant

  customize: !include customize.yaml

  packages: !include_dir_named integrations
#################################### OLD ############################################
#group: !include groups.yaml
#automation: !include automations.yaml
#device_tracker: !include trackers.yaml
#light: !include lights.yaml
#sensor: !include sensors.yaml
#switch: !include switches.yaml
#weather: !include weather.yaml
#media_player: !include media_player.yaml
#camera: !include cameras.yaml
#script: !include scripts.yaml
#notify: !include notify.yaml
#panel_iframe: !include panels.yaml
#keyboard_remote: !include keyboard_remotes.yaml
