- platform: ddwrt
  host: !secret Camille_IP
  username: !secret tomato_admin_user
  password: !secret tomato_admin_pass
  wireless_only: true
  interval_seconds: 60
  consider_home: 180
  new_device_defaults:
    track_new_devices: false
