#Sheldon
- platform: mjpeg
  name: "Harvest NightCam Mjpeg"
  #still_image_url: http://10.0.1.31/picture/1/frame/
  mjpeg_url: http://10.0.1.31:8081/mjpeg
  verify_ssl: false

#Hank
#Power Issues?
#- platform: mjpeg
#  name: "Tent CornerCam Mjpeg"
#  still_image_url: http://10.0.1.32/picture/1/current/
#  mjpeg_url: http://10.0.1.32:8081/mjpeg
#  verify_ssl: false
#- platform: mjpeg
#  name: "Harvest SkyCam Mjpeg"
#  still_image_url: http://10.0.1.32/picture/2/current/
#  mjpeg_url: http://10.0.1.32:8082/mjpeg
#  verify_ssl: false

#Richard
- platform: mjpeg
  name: "Harvest SideCam Mjpeg"
  #still_image_url: http://10.0.1.34/picture/1/current/
  still_image_url: http://10.0.1.34/picture/1/current/?_username=admin&_signature=9914267e3869f294b2f338389c17f1e0131ab402
  mjpeg_url: http://10.0.1.34:8081/mjpeg
- platform: mjpeg
  name: "Harvest TopCam Mjpeg"
  #still_image_url: http://10.0.1.34/picture/2/current/
  still_image_url: http://10.0.1.34/picture/2/current/?_username=admin&_signature=9914267e3869f294b2f338389c17f1e0131ab402
  mjpeg_url: http://10.0.1.34:8082/mjpeg
- platform: mjpeg
  name: "Tent CornerCam Mjpeg"
  #still_image_url: http://10.0.1.34/picture/3/current/
  still_image_url: http://10.0.1.34/picture/3/current/?_username=admin&_signature=9914267e3869f294b2f338389c17f1e0131ab402
  mjpeg_url: http://10.0.1.34:8083/mjpeg

#Cecilia
- platform: mjpeg
  name: "Tent PiCam Mjpeg"
  #still_image_url: http://10.0.1.30/picture/1/current/
  mjpeg_url: http://10.0.1.30:8081/mjpeg
  verify_ssl: false

#Dumdy
- platform: mjpeg
  name: "BrewerCam"
  still_image_url: "http://10.0.0.83:8080?action=snapshot"
  #mjpeg_url: http://10.0.0.30:8080/
  mjpeg_url: "http://10.0.0.83:8080?action=stream"
  verify_ssl: false

  #Clancy
#- platform: mjpeg
#  name: "Closet PiCam Mjpeg"
#  #still_image_url: http://10.0.1.33/picture/1/frame/
#  mjpeg_url: http://10.0.1.33:8081/mjpeg
#  verify_ssl: false
##- platform: mjpeg
##  name: "Closet Eye"
##  still_image_url: http://10.0.1.33/picture/2/current/
##  mjpeg_url: http://10.0.1.33:8082/mjpeg
##  verify_ssl: false
##- platform: generic
##  name: "Closet PiCam"
##  still_image_url: http://10.0.1.33/picture/1/frame
##  stream_source: rtsp://10.0.1.33:554
##  verify_ssl: false

#DISABLED
#############################################################################
#- platform: generic
#  name: "BrewerCam RTSP"
#  still_image_url: 'http://10.0.0.30:8080?action=snapshot'
#  stream_source: 'rtsp://10.0.0.30:554'
#  verify_ssl: false

#- platform: mjpeg
#  name: "Tent SkyCam"
#  still_image_url: http://10.0.1.30/picture/1/current/
#  mjpeg_url: http://10.0.1.30:8081/mjpeg
#  verify_ssl: false

#- platform: generic
#  name: "HarvestCam"
#  still_image_url: http://10.50.1.31/picture/1/current/
#  stream_source: http://10.50.1.31:8081/mjpeg
#  verify_ssl: false
#  framerate: 2

#- platform: mjpeg
#  name: "Tent HangCam"
#  still_image_url: http://10.0.1.30/picture/2/current/
#  stream_source: http://10.0.1.30:8082/mjpeg
#  verify_ssl: false
#  framerate: 2

#- platform: mjpeg
#  name: "Tent CornerCam"
#  still_image_url: http://10.0.1.30/picture/1/current/
#  stream_source: http://10.0.1.30:8081/mjpeg
#  verify_ssl: false
#  framerate: 2

#- platform: generic
#  name: "Tent PiCam"
#  still_image_url:
#  stream_source:
#  verify_ssl: false
#  framerate: 1
