- platform: mjpeg
  name: "Harvest NightCam"
  still_image_url: http://10.50.1.31/picture/1/current/
  mjpeg_url: http://10.50.1.31:8081/mjpeg
  verify_ssl: false
  
- platform: mjpeg
  name: "Tent CornerCam"
  still_image_url: http://10.50.1.32/picture/1/current/
  mjpeg_url: http://10.50.1.32:8081/mjpeg
  verify_ssl: false

#- platform: mjpeg
#  name: "Harvest CloseupCam"
#  still_image_url: http://10.50.1.32/picture/2/current/
#  mjpeg_url: http://10.50.1.32:8082/mjpeg
#  verify_ssl: false

- platform: mjpeg
  name: "Tent PoleCam"
  still_image_url: http://10.50.1.30/picture/2/current/
  mjpeg_url: http://10.50.1.30:8082/mjpeg
  verify_ssl: false
  
- platform: mjpeg
  name: "Tent SkyCam"
  still_image_url: http://10.50.1.30/picture/1/current/
  mjpeg_url: http://10.50.1.30:8081/mjpeg
  verify_ssl: false

- platform: combined
  base_address: https://homeassistant.ourhouse.services/
  #base_address: http://hassio.cirfis.org:8123/
  entities:
    - camera.tent_cornercam
    - camera.harvest_nightcam
    - camera.tent_skycam
#    - camera.harvest_closeupcam
    - camera.tent_polecam
  name: Grow Feeds Combined
    
#- platform: generic
#  name: "HarvestCam"
#  still_image_url: http://10.50.1.31/picture/1/current/
#  stream_source: http://10.50.1.31:8081/mjpeg
#  verify_ssl: false
#  framerate: 2

  
#- platform: mjpeg
#  name: "Tent HangCam"
#  still_image_url: http://10.50.1.30/picture/2/current/
#  stream_source: http://10.50.1.30:8082/mjpeg
#  verify_ssl: false
#  framerate: 2
  
#- platform: mjpeg
#  name: "Tent CornerCam"
#  still_image_url: http://10.50.1.30/picture/1/current/
#  stream_source: http://10.50.1.30:8081/mjpeg
#  verify_ssl: false
#  framerate: 2

#- platform: generic
#  name: "Tent PiCam"
#  still_image_url: 
#  stream_source: 
#  verify_ssl: false
#  framerate: 1
