binary_sensor:
  - platform: template
    sensors:
      irrigation_zone1:
        friendly_name: Irrigation State
        value_template: "{{ is_state('switch.irrigation_zone1','on') }}"

input_text:
  irrigation_zone1_times:
    name: List of Times (eg. 08:00,12:00,15:00)
    icon: mdi:clock-outline

input_number:
  irrigation_zone1_duration:
    name: Duration in Minutes
    icon: mdi:timer-sand
    min: 0
    max: 60
    step: 1
    unit_of_measurement: "minutes"