- alias: Perform Auto Backup
  trigger:
    platform: time_pattern # Perform backup every 3 hours.
    hours: "/3"
  action:
    service: auto_backup.backup_partial # Only perform a partial snapshot to save storage.
    data:
      name: "AutoBackup: {{ now().strftime('%a, %-I:%M %p (%d/%m/%Y)') }}"
      addons:
        - mariadb # It doesn't matter if you use the addon slug or name.
        #- bitwarden
        - chrony
        - a0d7b954_vscode
      folders:
        - homeassistant
        - share
        - ssl
      keep_days: 2

- alias: Perform Daily Backup
  trigger:
    platform: time
    at: "02:30:00"
  condition:
    condition: time # Perform backup every day except Mondays.
    weekday:
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
    service: auto_backup.backup_full
    data:
      name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 7

- alias: Perform Weekly Backup
  trigger:
    platform: time
    at: "02:30:00"
  condition:
    condition: time # On Mondays perform a weekly backup
    weekday:
      - mon
  action:
    service: auto_backup.snapshot_full
    data:
      name: "WeeklyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 28 # Store backup for a month, basically perform 1 backup each week and store for 4 weeks.

