- alias: "Create snapshot & Folder rsyncd to xanadul::hassio_backups"
  trigger:
    platform: time
    at: '1:00:00'
  action:
  - service: hassio.addon_start
    data:
      addon: 36883ed7_remote_backup
