- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_temperature
    - type: processor_use
    - type: ipv4_address
      arg: enp2s1
    - type: ipv6_address
      arg: enp2s1
    - type: network_in
      arg: enp2s1
    - type: network_out
      arg: enp2s1

