binary_sensor:
  - platform: template
    sensors:
      irrigation_zone1:
        friendly_name: Tent Irrigation State
        value_template: "{{ is_state('switch.irrigation_zone1','on') }}"
  - platform: template
    sensors:
      irrigation_zone2:
        friendly_name: Harvest Irrigation State
        value_template: "{{ is_state('switch.irrigation_zone2','on') }}"

input_text:
  irrigation_zone1_times:
    name: Tent Irrigation Times (eg. 08:00,12:00,15:00) [MUST be Low --> High]
    icon: mdi:chart-timeline
  irrigation_zone2_times:
    name: Harvest Irrigation Times (eg. 08:00,12:00,15:00) [MUST be Low --> High]
    icon: mdi:chart-timeline

  irrigation_zone1_days:
    name: Tent Irrigation Days (eg. Mon,THU,sat) [Must be Mon-->SUN]
    #icon: mdi:timelapse
    icon: mdi:calendar-week
  irrigation_zone2_days:
    name: Harvest Irrigation Days (eg. MON --> sun)
    #icon: mdi:timelapse
    icon: mdi:calendar-week

input_number:
  irrigation_zone1_duration:
    name: Tent Duration
    icon: mdi:timer-sand
    min: 0
    max: 300
    step: 1
    mode: box
    unit_of_measurement: "seconds"
  irrigation_zone2_duration:
    name: Harvest Duration
    icon: mdi:timer-sand
    min: 0
    max: 300
    mode: box
    step: 1
    unit_of_measurement: "seconds"
